CREATE DATABASE COFFEE;
USE COFFEE;



-- Monday Coffee SCHEMAS

DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS city;

-- Import Rules
-- 1st import to city
-- 2nd import to products
-- 3rd import to customers
-- 4th import to sales


CREATE TABLE city
(
	city_id	INT PRIMARY KEY,
	city_name VARCHAR(15),	
	population	BIGINT,
	estimated_rent	FLOAT,
	city_rank INT
);

CREATE TABLE customers
(
	customer_id INT PRIMARY KEY,	
	customer_name VARCHAR(25),	
	city_id INT,
	CONSTRAINT fk_city FOREIGN KEY (city_id) REFERENCES city(city_id)
);


CREATE TABLE products
(
	product_id	INT PRIMARY KEY,
	product_name VARCHAR(35),	
	Price float
);


CREATE TABLE sales
(
	sale_id	INT PRIMARY KEY,
	sale_date	date,
	product_id	INT,
	customer_id	INT,
	total FLOAT,
	rating INT,
	CONSTRAINT fk_products FOREIGN KEY (product_id) REFERENCES products(product_id),
	CONSTRAINT fk_customers FOREIGN KEY (customer_id) REFERENCES customers(customer_id) 
);

-- END of SCHEMAS



-- MONDAY COFFEE DATA ANALYSIS

-- 1)COFFE CONSUMES COUNT
-- HOW MANY PEOPLE IN EACH CITY ARE ESTIMATED TO CONSUME COFFEE,GIVE THAT 25% OF TH POPULATION DOES?
SELECT 
    CITY_NAME,
    ROUND(POPULATION*0.25/1000000,2) AS 'COFFE_CONSUMERS_IN_MILLIONS',
    CITY_RANK
FROM CITY 
ORDER BY POPULATION DESC;

-- 2)TOTAL REVENUE FROM COFFEE SALES
-- WHAT IS THE TOTAL REVENUE GENERAED FROM COFFE SALES ACROSS ALL CITIES IN THE LAST QURTER OF 2023?
SELECT *,
     SUM(TOTAL) AS 'REVENUE',
     YEAR(SALE_DATE) AS 'YEAR',
     QUARTER(SALE_DATE) AS 'QUARTER'
FROM SALES
WHERE 
	 YEAR(SALE_DATE) = 2023
     AND
     QUARTER(SALE_DATE) =  4
GROUP BY CITY_NAME;

-- 3)Sales Count For Each Product
-- How Many units of Each coffee product have been sold

SELECT 
     P.PRODUCT_NAME,
     COUNT(S.SALE_ID) AS TOTAL_ORDERS
FROM PRODUCTS AS P
LEFT JOIN
SALES AS S
ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_ORDERS DESC LIMIT 2;


-- 4) Average Sales Amount per City
-- What is the average sales amount per customer in each city
-- CITY AND TOTAL SALE
-- NO. OF  CUSTOMER IN EACH THESE CITY
SELECT 
	 C.CITY_NAME,
    ROUND(SUM(S.TOTAL) /(COUNT(DISTINCT(CS.CUSTOMER_ID))) )AS 'AVG_SALE_PR_CX'
FROM CITY AS C
JOIN 
CUSTOMERS AS CS
ON C.CITY_ID = CS.CITY_ID
JOIN 
SALES AS S
ON CS.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY CITY_NAME
ORDER BY SUM(TOTAL) DESC LIMIT 3;


-- 5)CITY PUPULATION AND COFFE CONSUMERS (25%)
-- PROVIDE A LIST OF CITIES ALONG WITH THEIR POPULATION AND ESTIMATED COFFEE CONSUMERS
-- RETURN CITY_NAME,TOTAL CURRENT CX,ESTIMATED COFFEE CONSUMERS(25%)

WITH CITY_TABLE AS 
(SELECT 
     city_name,
     ROUND(POPULATION*0.25/1000000,2) AS 'COFFE_CONSUMERS'
FROM CITY),

CUSTOMER_TABLE
AS
(SELECT 
     CI.CITY_NAME,
     COUNT(DISTINCT C.CUSTOMER_ID) AS UNIQUE_CX
FROM SALES AS S
JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID = S.CUSTOMER_ID
JOIN CITY AS CI 
ON CI.CITY_ID = C.CITY_ID
GROUP BY CITY_NAME)

SELECT 
     CT.CITY_NAME,
     CT.COFFE_CONSUMERS AS 'COFFE_CONSUMERS_IN_MILLION',
     CIT.UNIQUE_CX
FROM CITY_TABLE AS CT
JOIN 
CUSTOMER_TABLE AS CIT
ON CT.CITY_NAME = CIT.CITY_NAME;

-- 6)TOP SELLING PRODUCT BY CITY
-- WHAT ARE THE TOP  3 SELLING PRODUCT  IN EACH CITY BASED ON SALES VOLUME?
SELECT * FROM
(
    SELECT 
        CI.CITY_NAME,
        P.PRODUCT_NAME,
        COUNT(S.SALE_ID) AS TOTAL_SALES,
        DENSE_RANK() OVER(
            PARTITION BY CI.CITY_NAME 
            ORDER BY COUNT(S.SALE_ID) DESC
        ) AS 'RANK'
    FROM SALES AS S 
    JOIN PRODUCTS AS P
        ON S.PRODUCT_ID = P.PRODUCT_ID
    JOIN CUSTOMERS AS C
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    JOIN CITY AS CI
        ON CI.CITY_ID = C.CITY_ID
    GROUP BY CI.CITY_NAME, P.PRODUCT_NAME
) AS T1
WHERE 'RANK' <= 3;



    








